### ISSUE TITLE
Unable to run pipeline.sh

### ISSUE THREAD

**Issue by pidugusundeep** [martiansideofthemoon/squash-generation#14]
```
Run 1 ...
Choosing instance from QuAC dev set ...
quac_785
Extracting answers ...
Generating questions ...
INFO:question-generation/interact.py:Namespace(device='cpu', filename='squash/temp/quac_785/input.pkl', key='quac_785', max_length=50, min_length=1, model_c
heckpoint='question-generation/gpt2_corefs_question_generation', model_type='gpt2', no_sample=False, seed=42, temperature=0.7, top_k=0, top_p=0.9)
INFO:question-generation/interact.py:Get pretrained model and tokenizer
ERROR:pytorch_pretrained_bert.tokenization_gpt2:Model name 'question-generation/gpt2_corefs_question_generation' was not found in model name list (gpt2, gpt
2-medium). We assumed 'question-generation/gpt2_corefs_question_generation' was a path or url but couldn't find files question-generation/gpt2_corefs_questi
on_generation/vocab.json and question-generation/gpt2_corefs_question_generation/merges.txt at this path or url.
ERROR:pytorch_pretrained_bert.modeling_gpt2:Model name 'question-generation/gpt2_corefs_question_generation' was not found in model name list (gpt2, gpt2-me
dium). We assumed 'question-generation/gpt2_corefs_question_generation' was a path or url but couldn't find files question-generation/gpt2_corefs_question_g
eneration/pytorch_model.bin and question-generation/gpt2_corefs_question_generation/config.json at this path or url.
cpu
Traceback (most recent call last):
  File "question-generation/interact.py", line 242, in <module>
    run()
  File "question-generation/interact.py", line 153, in run
    model.eval()
AttributeError: 'NoneType' object has no attribute 'eval'
Running QA module ...
Namespace(bert_model='question-answering//bert_large_qa_model', do_lower_case=True, do_predict=True, do_train=False, doc_stride=128, fp16=False, gradient_accumulation_steps=1, learning_rate=5e-05, local_rank=-1, loss_scale=0, max_answer_length=30, max_query_length=64, max_seq_length=384, n_best_size=20, no_cuda=False, null_score_diff_threshold=0.0, num_train_epochs=3.0, output_dir='squash/temp/quac_785', predict_batch_size=16, predict_file='squash/temp/quac_785/generated_questions.json', seed=42, server_ip='', server_port='', train_batch_size=32, train_file=None, verbose_logging=False, version_2_with_negative=True, warmup_proportion=0.1)
07/17/2019 12:24:48 - INFO - __main__ -   device: cpu n_gpu: 0, distributed training: False, 16-bits training: False
07/17/2019 12:24:48 - ERROR - pytorch_pretrained_bert.tokenization -   Model name 'question-answering//bert_large_qa_model' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'question-answering//bert_large_qa_model' was a path or url but couldn't find any file associated to this path or url.
07/17/2019 12:24:48 - ERROR - pytorch_pretrained_bert.modeling -   Model name 'question-answering//bert_large_qa_model' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'question-answering//bert_large_qa_model' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "question-answering/run_squad.py", line 1102, in <module>
    main()
  File "question-answering/run_squad.py", line 913, in main
    model.to(device)
AttributeError: 'NoneType' object has no attribute 'to'
Combining Q and A ...
Traceback (most recent call last):
  File "squash/combine_qa.py", line 11, in <module>
    with open('squash/temp/%s/generated_questions.json' % args.key, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'squash/temp/quac_785/generated_questions.json'
Filtering bad Q/As ...
Traceback (most recent call last):
  File "squash/filter.py", line 147, in <module>
    with open('squash/temp/%s/final_qa_set.json' % args.key, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'squash/temp/quac_785/final_qa_set.json'
```

It should be something to do with 
https://github.com/martiansideofthemoon/squash-generation/blob/d19fc5bafe7965d0d2509771b093e60695474743/question-generation/interact.py#L142-L147  
Please let me know how to fix this.

**Comment by martiansideofthemoon** [comment]
You have not loaded the pretrained question generation model correctly it seems. Also, make sure you run pipine.sh from the root directory `squash-generation`.
