### ISSUE TITLE
error while running "bash schedule_gpt.sh ," THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=37 error=101 : invalid device ordinal"

### ISSUE THREAD

**Issue by aravindchaluvadi** [martiansideofthemoon/squash-generation#29]
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
WARNING:question-generation/train.py:Running process 1
WARNING:question-generation/train.py:Running process 0
WARNING:question-generation/train.py:Running process 2
WARNING:question-generation/train.py:Running process 3
INFO:question-generation/train.py:Arguments: Namespace(dataset_cache='data/temp_dataset/cache', dataset_path='data/temp_dataset/instances', device='cuda', eval_before_start=False, fp16='', gradient_accumulation_steps=8, local_rank=0, lr=6.25e-05, max_norm=1.0, model_checkpoint='openai-gpt', n_epochs=4, output_dir='question-generation/gpt_question_generation', train_batch_size=4, valid_batch_size=4)
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=37 error=101 : invalid device ordinal
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=37 error=101 : invalid device ordinal
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=37 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 259, in train
    train()
  File "question-generation/train.py", line 259, in train
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 259, in train
    torch.cuda.set_device(args.local_rank)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/cuda/__init__.py", line 300, in set_device
    torch.cuda.set_device(args.local_rank)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/cuda/__init__.py", line 300, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:37
    torch.cuda.set_device(args.local_rank)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/cuda/__init__.py", line 300, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:37
    train()
  File "question-generation/train.py", line 261, in train
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:37
    torch.distributed.init_process_group(backend='nccl', init_method='env://')
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 400, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/xxxx/anaconda3/envs/squash/bin/python3', '-u', 'question-generation/train.py', '--local_rank=3', '--n_epochs', '4', '--output_dir', 'question-generation/gpt_question_generation']' returned non-zero exit status 1.

Can someone help me with this?

**Comment by aravindchaluvadi** [comment]
solved
