### ISSUE TITLE
Question generation

### ISSUE THREAD

**Issue by vapyc** [martiansideofthemoon/squash-generation#39]
Traceback (most recent call last):
  File "question-generation/interact.py", line 238, in <module>
    run()
  File "question-generation/interact.py", line 144, in run
    model = GPT2LMHeadModel.from_pretrained(args.model_checkpoint)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling_gpt2.py", line 475, in from_pretrained
    "Error(s) in loading state_dict for {}:\n\t{}".format(model.__class__.__name__, "\n\t".join(error_msgs))
RuntimeError: Error(s) in loading state_dict for GPT2LMHeadModel:
	size mismatch for transformer.wte.weight: copying a param with shape torch.Size([50265, 768]) from checkpoint, the shape in current model is torch.Size([50257, 768]).
	size mismatch for lm_head.decoder.weight: copying a param with shape torch.Size([50265, 768]) from checkpoint, the shape in current model is torch.Size([50257, 768]).

I am getting this error while running interact.py

**Comment by vapyc** [comment]
Here is the complete execution
```INFO:question-generation/interact.py:Namespace(device='cpu', filename='squash/temp/quac_869/input.pkl', key='quac_869', max_length=50, min_length=1, model_checkpoint='/content/question-generation/gpt2_corefs_question_generation', model_type='gpt2', no_sample=False, seed=42, temperature=0.7, top_k=0, top_p=0.9)
INFO:question-generation/interact.py:Get pretrained model and tokenizer
INFO:pytorch_pretrained_bert.tokenization_gpt2:loading special tokens file /content/question-generation/gpt2_corefs_question_generation/special_tokens.txt
INFO:pytorch_pretrained_bert.tokenization_gpt2:loading vocabulary file /content/question-generation/gpt2_corefs_question_generation/vocab.json
INFO:pytorch_pretrained_bert.tokenization_gpt2:loading merges file /content/question-generation/gpt2_corefs_question_generation/merges.txt
INFO:pytorch_pretrained_bert.tokenization_gpt2:Special tokens {'<bos>': 50257, '<eos>': 50258, '<paragraph>': 50259, '<answer-general>': 50260, '<answer-specific>': 50261, '<question-general>': 50262, '<question-specific>': 50263, '<pad>': 50264}
INFO:pytorch_pretrained_bert.modeling_gpt2:loading weights file /content/question-generation/gpt2_corefs_question_generation/pytorch_model.bin
INFO:pytorch_pretrained_bert.modeling_gpt2:loading configuration file /content/question-generation/gpt2_corefs_question_generation/config.json
INFO:pytorch_pretrained_bert.modeling_gpt2:Model config {
  "attn_pdrop": 0.1,
  "embd_pdrop": 0.1,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 12,
  "n_positions": 1024,
  "n_special": 8,
  "predict_special_tokens": true,
  "resid_pdrop": 0.1,
  "vocab_size": 50257
}

Traceback (most recent call last):
  File "question-generation/interact.py", line 238, in <module>
    run()
  File "question-generation/interact.py", line 144, in run
    model = GPT2LMHeadModel.from_pretrained(args.model_checkpoint)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling_gpt2.py", line 475, in from_pretrained
    "Error(s) in loading state_dict for {}:\n\t{}".format(model.__class__.__name__, "\n\t".join(error_msgs))
RuntimeError: Error(s) in loading state_dict for GPT2LMHeadModel:
	size mismatch for transformer.wte.weight: copying a param with shape torch.Size([50265, 768]) from checkpoint, the shape in current model is torch.Size([50257, 768]).
	size mismatch for lm_head.decoder.weight: copying a param with shape torch.Size([50265, 768]) from checkpoint, the shape in current model is torch.Size([50257, 768]).
```

**Comment by vapyc** [comment]
got the solution
I did not perform
```
!pip install --editable .
```
