### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by vapyc** [martiansideofthemoon/squash-generation#41]
Hey, @martiansideofthemoon I trained a model on a custom dataset.  It completed the training but then threw this error.
```
100%|█████████████████████████████| 1042301/1042301 [00:00<00:00, 2046072.86B/s]
100%|███████████████████████████████| 456318/456318 [00:00<00:00, 1342293.77B/s]
100%|████████████████████████| 548118077/548118077 [00:22<00:00, 24830562.08B/s]
100%|██████████████████████████████████████| 554/554 [00:00<00:00, 350950.67B/s]
100%|██████████████████████████████████████| 9427/9427 [00:14<00:00, 650.39it/s]
100%|██████████████████████████████████████| 3270/3270 [00:03<00:00, 862.53it/s]
/opt/conda/lib/python3.6/site-packages/ignite/handlers/checkpoint.py:369: UserWarning: Argument save_interval is deprecated and should be None. Please, use events filtering instead, e.g. Events.ITERATION_STARTED(every=1000)
  warnings.warn(msg)
Validation: {'average_nll': 79.21129608154297,
 'average_ppl': 2.5178438488643437e+34,
 'nll': 79.21129882643015}
Validation: {'average_nll': 2.1138651371002197,                                 
 'average_ppl': 8.280183558895889,
 'nll': 2.1138651501822294}
Epoch: [4714/4714] 100%|██████████████████████████████, loss=0.154 [41:18<00:00]
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 371, in train
    os.rename(checkpoint_handler._saved[-1][1][-1], os.path.join(tb_logger.writer.log_dir, WEIGHTS_NAME))  # TODO: PR in ignite to have better access to saved file paths (cleaner)
FileNotFoundError: [Errno 2] No such file or directory: 'h' -> 'question-generation/gpt2_corefs_question_generations/pytorch_model.bin'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'question-generation/train.py', '--local_rank=0', '--eval_before_start', '--n_epochs=1', '--model_checkpoint', 'gpt2', '--train_batch_size', '2', '--valid_batch_size', '2', '--gradient_accumulation_steps', '16', '--dataset_path', 'data/temp_dataset/instances_corefs', '--dataset_cache', 'data/temp_dataset/cache_corefs', '--output_dir', 'question-generation/gpt2_corefs_question_generations']' returned non-zero exit status 1.
```
Can you guide me through this? Thanks in advance!!

**Comment by vapyc** [comment]
> Hey, @martiansideofthemoon I trained a model on a custom dataset. It completed the training but then threw this error.
> 
> ```
> 100%|█████████████████████████████| 1042301/1042301 [00:00<00:00, 2046072.86B/s]
> 100%|███████████████████████████████| 456318/456318 [00:00<00:00, 1342293.77B/s]
> 100%|████████████████████████| 548118077/548118077 [00:22<00:00, 24830562.08B/s]
> 100%|██████████████████████████████████████| 554/554 [00:00<00:00, 350950.67B/s]
> 100%|██████████████████████████████████████| 9427/9427 [00:14<00:00, 650.39it/s]
> 100%|██████████████████████████████████████| 3270/3270 [00:03<00:00, 862.53it/s]
> /opt/conda/lib/python3.6/site-packages/ignite/handlers/checkpoint.py:369: UserWarning: Argument save_interval is deprecated and should be None. Please, use events filtering instead, e.g. Events.ITERATION_STARTED(every=1000)
>   warnings.warn(msg)
> Validation: {'average_nll': 79.21129608154297,
>  'average_ppl': 2.5178438488643437e+34,
>  'nll': 79.21129882643015}
> Validation: {'average_nll': 2.1138651371002197,                                 
>  'average_ppl': 8.280183558895889,
>  'nll': 2.1138651501822294}
> Epoch: [4714/4714] 100%|██████████████████████████████, loss=0.154 [41:18<00:00]
> Traceback (most recent call last):
>   File "question-generation/train.py", line 375, in <module>
>     train()
>   File "question-generation/train.py", line 371, in train
>     os.rename(checkpoint_handler._saved[-1][1][-1], os.path.join(tb_logger.writer.log_dir, WEIGHTS_NAME))  # TODO: PR in ignite to have better access to saved file paths (cleaner)
> FileNotFoundError: [Errno 2] No such file or directory: 'h' -> 'question-generation/gpt2_corefs_question_generations/pytorch_model.bin'
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
>     main()
>   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
>     cmd=cmd)
> subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'question-generation/train.py', '--local_rank=0', '--eval_before_start', '--n_epochs=1', '--model_checkpoint', 'gpt2', '--train_batch_size', '2', '--valid_batch_size', '2', '--gradient_accumulation_steps', '16', '--dataset_path', 'data/temp_dataset/instances_corefs', '--dataset_cache', 'data/temp_dataset/cache_corefs', '--output_dir', 'question-generation/gpt2_corefs_question_generations']' returned non-zero exit status 1.
> ```
> 
> Can you guide me through this? Thanks in advance!!

Do I need to copy pytorch_model.bin file necessarily in the folder in which we are saving the model checkpoints?

**Comment by martiansideofthemoon** [comment]
Yeah I think this is necessary to load the model, I remember seeing something like this in the project I'm currently doing. It was a 1-line fix in the code if I remember correctly. You do not need to retrain the model and you should be able to still use the `interact.py` file using the respective checkpoint folder

**Comment by vapyc** [comment]
Well, I wanted to retrain on my dataset since I had a specific type of question that I wanted to generate.
```
  model_class = GPT2LMHeadModel if "gpt2" in args.model_checkpoint else OpenAIGPTLMHeadModel
    model = model_class.from_pretrained(args.model_checkpoint)
```
As per other issues using this automatically download the PyTorch bin but this doesn't seem to work in our case. I am looking for solving this but if you could find a fix then please post it. @martiansideofthemoon

**Comment by martiansideofthemoon** [comment]
> As per other issues using this automatically download the PyTorch bin but this doesn't seem to work in our case

What exactly is happening in our case?

**Comment by vapyc** [comment]
```
checkpoint_mymodel_4714.pth		     model_training_args.bin
config.json				     special_tokens.txt
events.out.tfevents.1589258707.2ab40f8c7b8c  vocab.json
merges.txt
```
This is a list of files created by the model after training and throwing the above the error.
All the files except pytorch_model.bin are created. Can't find why pytorch_model.bin is not created.

**Comment by martiansideofthemoon** [comment]
I think this is happening because `ignite` didn't copy the checkpoint file to `pytorch_model.bin`. It's unclear to me why this is happening, did you get this error on a custom dataset?

A simple fix for now could be to copy `checkpoint_mymodel_4714.pth` to `pytorch_model.bin`
